//This studies the orbit of Mercury around the Sun with no other planets present. The Sun is taken to be the COM of the system.
//This makes use of the planet and ODEsolver classes. For high resolution time steps, use the "odesolver_reduced_output.cpp" class file
//which reduces the output to file to only the last orbit of Mercury in order to make the file size manageable.

//The perihelion precession is studied by the matlab script "mercury_precession.m" which uses the output file generated by this code.

//No input from the command line is required.

//Coded by: Tim Golubev, Hao Lin, Xingze Mao

#define _USE_MATH_DEFINES
#include <iostream>
#include <cmath>
#include <string>
#include <fstream>  //for files
#include <random>
#include <chrono>
#include <time.h>
//#include "planet.h"   odesolver.h already includes planet.h
#include "odesolver.h"

using namespace std;
using namespace chrono;

int main()
{
    // Numerical setup
                    //int can hold only digits btw. ~2.1billion and -2.1billion if want full precision. Can use higher numbers if write as ie 5e9
    int integration_points = 100000000;  // # of integration points (Mercury requires 500k if simulate 100 earth years for more consistent thin orbit
                                       //and even higher for finding relativistic perihelion precession)
    double final_time = 100.;         // End time of calculation. (Mercury takes 88days for 1 orbit)
    bool corrections = true;          //Apply relativistic corrections to forces?
    bool sun_fixed = true;

    //Set-up planets, Using April 1st, positions and velocities in Au/year. Using Sun as origin.
    //NOTE: The Sun is at origin of coordinate system.
    planet planet1("Sun",1.,0.,0.,0.,0.,0.,0.);                     // planet1 (name,mass,x,y,z,vx,vy,vz), name must be in " " marks
    planet planet2("Mercury",1.65967823e-7,0.30749951,0.,0.,0.,12.433287,0.);  //using #'s given in part g
    //constants from http://www.newworldencyclopedia.org/entry/Mercury_(planet)
    //planet planet2("Mercury",1.65967823e-7,0.30749951,0.,0.,0.,12.44,0.);  //using #'s given in part g

    //Setup the system
    ODEsolver precession;         //create object of class ODEsolver with default constructor ODEsolver(). If put the () in declaration here, it doesn't work!
    precession.add(planet1);      //add planets to the solver
    precession.add(planet2);

    //Output the properties of the planets
    for(int i=0;i<precession.total_planets;i++)
    {
      cout << precession.all_planets[i].name << "'s Mass = " <<precession.all_planets[i].mass<< endl;
      cout << precession.all_planets[i].name <<"'s Initial Position = " << precession.all_planets[i].position[0] << ","
           << precession.all_planets[i].position[1]<<","<< precession.all_planets[i].position[2]<< endl;
    }
    //Tests of the setup
    //cout << "Gconst = " <<precession.Gconst << endl;
    //cout << "Number of Planets = " <<precession.total_planets<<endl;

    // Velocity Verlet
    //start clock timer
    high_resolution_clock::time_point start2 = high_resolution_clock::now();

    precession.VelocityVerlet(integration_points, final_time, corrections, sun_fixed); //Run VVerlet ODEsolver

    //stop clock timer and output time duration
    high_resolution_clock::time_point finish2 = high_resolution_clock::now();
    duration<double> time2 = duration_cast<duration<double>>(finish2-start2);
    cout << "Velocity Verlet Solver CPU time = " << time2.count() << endl;

    return 0;
}

